const GENERAL = {
  ACTIONS: {
    SET_ETO_DATA: 'SET_ETO_DATA',
    SET_ETO_PROPERTY: 'SET_ETO_PROPERTY',
    SET_ETO_BLOCKS: 'SET_ETO_BLOCKS',
  },
  FORMATS: {
    DATE_FORMAT: 'DD-MM-YYYY',
  },
};

export default GENERAL;
